apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260616-200219-se40c8u1g8ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260616-200219-se40c8u1g8ui.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260616-200219-se40c8u1g8ui-service
            port:
              number: 80
