apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260616-200219-se40c8u1g8ui-service
spec:
  selector:
    app: enterprise-system-20260616-200219-se40c8u1g8ui
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
